server:
  port: 7999
spring:
  application:
    name: comments
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway crea las migraciones, Hibernate valida
  flyway:
    enabled: true

  profiles:
    active:
      - "dev"
